#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

start_service() {
	local lan_ip
	lan_ip="$(ubus call network.interface.lan status 2>/dev/null | jsonfilter -e '@["ipv4-address"][0].address')"
	[ -n "$lan_ip" ] || lan_ip="$(uci -q get network.lan.ipaddr)"
	[ -n "$lan_ip" ] || return 1

	/usr/libexec/usb-power-control init || return 1

	procd_open_instance web
	procd_set_param command /usr/sbin/uhttpd -f \
		-p "$lan_ip:54199" \
		-h /www/usb-power \
		-x /cgi-bin \
		-t 10 -T 10 -k 10 -A 1 -n 8 -N 16
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance

	procd_open_instance thermal
	procd_set_param command /usr/libexec/usb-power-thermal
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	/usr/libexec/usb-power-control release
}

service_triggers() {
	procd_add_reload_trigger usbpower
}

reload_service() {
	/usr/libexec/usb-power-control reconcile
}
